"""
Django settings for backend project.

Generated by "django-admin startproject" using Django 3.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / "subdir".
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-4h(4(tkle+h!x*81b(r9!!z4jous7ld3!nwfx7ra^w39!z2vls"

# SECURITY WARNING: don"t run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_filters",
    "drf_spectacular",
    "rest_framework",
    "api.apps.ApiConfig",
    "apps.apps.AppsConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "conf.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "conf.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# 작업 주의사항 : sqlite가 아닌 MySQL 설정으로 변경해 주세요
DATABASES = {
    "default" : {
        "ENGINE" : "django.db.backends.mysql",
        "NAME" : os.environ["DATABASE"],
        "USER" : os.environ["USER"],
        "PASSWORD" : os.environ["PASSWORD"],
        "HOST" : os.environ["HOST"],
        "PORT" : 3306,
        "OPTIONS" : {
            "init_command" : 'SET sql_mode="STRICT_TRANS_TABLES"',
        }
    },
}


LOGGING = {
    "version" : 1,
    "disable_existing_loggers" : False,
    "formatters" : {
        "default_format" : {
            "format" : \
                "%(asctime)s %(levelname)s " \
                "[%(name)s] [%(filename)s:%(lineno)d] " \
                "- %(message)s",
        },
    },
    "handlers" : {
        "console" : {
            "level" : "INFO",
            "class" : "logging.StreamHandler",
            "formatter" : "default_format",
        },
    },
    "root" : {
        "handlers" : ["console"],
        "level" : "INFO",
    },
}

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "ko-kr"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_L10N = True

USE_TZ = True


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES" : [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PARSER_CLASSES" : [
        "rest_framework.parsers.JSONParser",
    ],
    "DEFAULT_FILTER_BACKENDS" : [
        "rest_framework.filters.OrderingFilter",
    ],
    
    "DEFAULT_PAGINATION_CLASS" : "rest_framework.pagination.CursorPagination",
    "PAGE_SIZE" : 5,
    "DEFAULT_SCHEMA_CLASS" : "drf_spectacular.openapi.AutoSchema",
}


SPECTACULAR_SETTINGS = {
    "TITLE": "주소록 API",
    "DESCRIPTION": "연락처 및 라벨의 CRUD와 연락처에 라벨 적용하는 API를 담고 있습니다.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}