-- 연락처 데이터
INSERT INTO `kidsnote_contact`.`tb_contact` (`contact_id`, `profile`, `name`, `email`, `phone`, `company`, `position`, `memo`, `address`, `birthday`, `website`) VALUES ('1', 'https://www.gstatic.com/identity/boq/profilepicturepicker/photo_silhouette_e02a5f5deb3ffc173119a01bc9575490.png', '강건우', 'yunseo28@example.com', '055-386-9875', '(주) 장이윤', '도장공', '', '경기도 증평군 봉은사536가', '2001-10-03', '');
INSERT INTO `kidsnote_contact`.`tb_contact` (`contact_id`, `profile`, `name`, `email`, `phone`, `company`, `position`, `memo`, `address`, `birthday`, `website`) VALUES ('2', 'https://www.gstatic.com/identity/boq/profilepicturepicker/photo_silhouette_e02a5f5deb3ffc173119a01bc9575490.png', '권은주', 'seonghun83@example.org', '044-795-6672', '유한회사 최', '주유원', '', '인천광역시 동작구 양재천거리', '1921-09-29', '');
INSERT INTO `kidsnote_contact`.`tb_contact` (`contact_id`, `profile`, `name`, `email`, `phone`, `company`, `position`, `memo`, `address`, `birthday`, `website`) VALUES ('3', 'https://www.gstatic.com/identity/boq/profilepicturepicker/photo_silhouette_e02a5f5deb3ffc173119a01bc9575490.png', '김우진', 'donghyeonseo@example.net', '052-653-2951', '김지신', '의사', '', '경상북도 청주시 서원구 논현6길', '1997-05-18', '');
INSERT INTO `kidsnote_contact`.`tb_contact` (`contact_id`, `profile`, `name`, `email`, `phone`, `company`, `position`, `memo`, `address`, `birthday`, `website`) VALUES ('4', 'https://www.gstatic.com/identity/boq/profilepicturepicker/photo_silhouette_e02a5f5deb3ffc173119a01bc9575490.png', '이영환', 'ui@example.org', '055-834-3414', '김강', '자산 운용가', '', '광주광역시 강남구 오금가', '1918-06-13', '');
INSERT INTO `kidsnote_contact`.`tb_contact` (`contact_id`, `profile`, `name`, `email`, `phone`, `company`, `position`, `memo`, `address`, `birthday`, `website`) VALUES ('5', 'https://www.gstatic.com/identity/boq/profilepicturepicker/photo_silhouette_e02a5f5deb3ffc173119a01bc9575490.png', '박시우', 'seunghyeonsong@example.net', '018-257-3986', '김윤', '조작원', '', '서울특별시 은평구 영동대996길 (영철이동)', '1927-04-19', '');
INSERT INTO `kidsnote_contact`.`tb_contact` (`contact_id`, `profile`, `name`, `email`, `phone`, `company`, `position`, `memo`, `address`, `birthday`, `website`) VALUES ('6', 'https://www.gstatic.com/identity/boq/profilepicturepicker/photo_silhouette_e02a5f5deb3ffc173119a01bc9575490.png', '노지현', 'jia77@example.com', '052-186-2045', '(주) 이', '시험원', '', '충청북도 양구군 봉은사로 (우진고김면)', '2005-05-21', '');
INSERT INTO `kidsnote_contact`.`tb_contact` (`contact_id`, `profile`, `name`, `email`, `phone`, `company`, `position`, `memo`, `address`, `birthday`, `website`) VALUES ('7', 'https://www.gstatic.com/identity/boq/profilepicturepicker/photo_silhouette_e02a5f5deb3ffc173119a01bc9575490.png', '박정웅', 'hanjia@example.org', '055-662-6801', '유한회사 김박이', '관리자', 'Voluptatem eveniet', '경상북도 부천시 소사구 백제고분899길 (현우박마을)', '1959-05-12', '');
INSERT INTO `kidsnote_contact`.`tb_contact` (`contact_id`, `profile`, `name`, `email`, `phone`, `company`, `position`, `memo`, `address`, `birthday`, `website`) VALUES ('8', 'https://www.gstatic.com/identity/boq/profilepicturepicker/photo_silhouette_e02a5f5deb3ffc173119a01bc9575490.png', '이보람', 'ujang@example.net', '033-425-6142', '(유) 이', '기계조작원', '', '인천광역시 은평구 서초대791가 (수빈허동)', '2022-11-14', '');
INSERT INTO `kidsnote_contact`.`tb_contact` (`contact_id`, `profile`, `name`, `email`, `phone`, `company`, `position`, `memo`, `address`, `birthday`, `website`) VALUES ('9', 'https://www.gstatic.com/identity/boq/profilepicturepicker/photo_silhouette_e02a5f5deb3ffc173119a01bc9575490.png', '오상철', 'jeongsig06@example.net', '018-490-5604', '김안', '담배 등급원', '', '', '1972-11-13', 'https://www.imgim.net/');
INSERT INTO `kidsnote_contact`.`tb_contact` (`contact_id`, `profile`, `name`, `email`, `phone`, `company`, `position`, `memo`, `address`, `birthday`, `website`) VALUES ('10', 'https://www.gstatic.com/identity/boq/profilepicturepicker/photo_silhouette_e02a5f5deb3ffc173119a01bc9575490.png', '김하은', 'eunseo67@example.com', '032-553-0262', '(유) 김', '생산기 조작원', '', '인천광역시 강북구 석촌호수거리', '1948-02-19', '');
INSERT INTO `kidsnote_contact`.`tb_contact` (`contact_id`, `profile`, `name`, `email`, `phone`, `company`, `position`, `memo`, `address`, `birthday`, `website`) VALUES ('11', 'https://www.gstatic.com/identity/boq/profilepicturepicker/photo_silhouette_e02a5f5deb3ffc173119a01bc9575490.png', '박명숙', 'gimseongho@example.org', '070-8669-7008', '이이', '수선원', '', '대전광역시 강동구 개포45길 (성호윤동)', '1998-03-22', '');
INSERT INTO `kidsnote_contact`.`tb_contact` (`contact_id`, `profile`, `name`, `email`, `phone`, `company`, `position`, `memo`, `address`, `birthday`, `website`) VALUES ('12', 'https://www.gstatic.com/identity/boq/profilepicturepicker/photo_silhouette_e02a5f5deb3ffc173119a01bc9575490.png', '김영수', 'qi@example.com', '044-639-9369', '(주) 김', '미용사', '', '', '1948-05-20', '');
INSERT INTO `kidsnote_contact`.`tb_contact` (`contact_id`, `profile`, `name`, `email`, `phone`, `company`, `position`, `memo`, `address`, `birthday`, `website`) VALUES ('13', 'https://www.gstatic.com/identity/boq/profilepicturepicker/photo_silhouette_e02a5f5deb3ffc173119a01bc9575490.png', '이준영', 'cunja11@example.org', '044-814-9997', '김한', '정비원', '', '충청북도 수원시 권선구 백제고분로 (지영김백읍)', '1986-02-11', '');
INSERT INTO `kidsnote_contact`.`tb_contact` (`contact_id`, `profile`, `name`, `email`, `phone`, `company`, `position`, `memo`, `address`, `birthday`, `website`) VALUES ('14', 'https://www.gstatic.com/identity/boq/profilepicturepicker/photo_silhouette_e02a5f5deb3ffc173119a01bc9575490.png', '신영순', 'gangseonghyeon@example.net', '053-444-6743', '윤이', '연구원', '', '제주특별자치도 옥천군 선릉거리', '1972-04-18', '');
INSERT INTO `kidsnote_contact`.`tb_contact` (`contact_id`, `profile`, `name`, `email`, `phone`, `company`, `position`, `memo`, `address`, `birthday`, `website`) VALUES ('15', 'https://www.gstatic.com/identity/boq/profilepicturepicker/photo_silhouette_e02a5f5deb3ffc173119a01bc9575490.png', '박동현', 'iyunseo@example.net', '061-592-7954', '김이', '제조원', '', '대구광역시 송파구 선릉길', '1953-08-09', '');
INSERT INTO `kidsnote_contact`.`tb_contact` (`contact_id`, `profile`, `name`, `email`, `phone`, `company`, `position`, `memo`, `address`, `birthday`, `website`) VALUES ('16', 'https://www.gstatic.com/identity/boq/profilepicturepicker/photo_silhouette_e02a5f5deb3ffc173119a01bc9575490.png', '홍서현', 'jgim@example.org', '02-3479-7121', '유한회사 서최고', '관리자', '', '', '1946-02-17', 'gimyeongsu@naver.com');
INSERT INTO `kidsnote_contact`.`tb_contact` (`contact_id`, `profile`, `name`, `email`, `phone`, `company`, `position`, `memo`, `address`, `birthday`, `website`) VALUES ('17', 'https://www.gstatic.com/identity/boq/profilepicturepicker/photo_silhouette_e02a5f5deb3ffc173119a01bc9575490.png', '김민수', 'hyeonjui@example.org', '019-774-6132', '권오이', '조작원', '', '', '1933-08-30', '');
INSERT INTO `kidsnote_contact`.`tb_contact` (`contact_id`, `profile`, `name`, `email`, `phone`, `company`, `position`, `memo`, `address`, `birthday`, `website`) VALUES ('18', 'https://www.gstatic.com/identity/boq/profilepicturepicker/photo_silhouette_e02a5f5deb3ffc173119a01bc9575490.png', '노성현', 'bagjunho@example.net', '051-137-6864', '주식회사 권', '예능 강사', '', '대구광역시 구로구 논현로 (상철강마을)', '2021-05-29', '');
INSERT INTO `kidsnote_contact`.`tb_contact` (`contact_id`, `profile`, `name`, `email`, `phone`, `company`, `position`, `memo`, `address`, `birthday`, `website`) VALUES ('19', 'https://www.gstatic.com/identity/boq/profilepicturepicker/photo_silhouette_e02a5f5deb3ffc173119a01bc9575490.png', '박현지', 'minjae26@example.org', '032-797-1176', '(주) 이이노', '조리사', '', '', '1946-01-21', '');
INSERT INTO `kidsnote_contact`.`tb_contact` (`contact_id`, `profile`, `name`, `email`, `phone`, `company`, `position`, `memo`, `address`, `birthday`, `website`) VALUES ('20', 'https://www.gstatic.com/identity/boq/profilepicturepicker/photo_silhouette_e02a5f5deb3ffc173119a01bc9575490.png', '강진우', 'jeonghun17@example.com', '019-184-0383', '주식회사 박문김', '경비원', '', '대구광역시 강동구 서초중앙로', '1961-12-30', '');
INSERT INTO `kidsnote_contact`.`tb_contact` (`contact_id`, `profile`, `name`, `email`, `phone`, `company`, `position`, `memo`, `address`, `birthday`, `website`) VALUES ('21', 'https://www.gstatic.com/identity/boq/profilepicturepicker/photo_silhouette_e02a5f5deb3ffc173119a01bc9575490.png', '박영자', 'gangseongho@example.com', '043-916-5091', '유한회사 최', '소방관', '', '', '1998-11-27', '');
INSERT INTO `kidsnote_contact`.`tb_contact` (`contact_id`, `profile`, `name`, `email`, `phone`, `company`, `position`, `memo`, `address`, `birthday`, `website`) VALUES ('22', 'https://www.gstatic.com/identity/boq/profilepicturepicker/photo_silhouette_e02a5f5deb3ffc173119a01bc9575490.png', '박수민', 'yeongsubag@example.net', '044-872-0202', '이장', '단열공', '', '', '1980-01-08', '');
INSERT INTO `kidsnote_contact`.`tb_contact` (`contact_id`, `profile`, `name`, `email`, `phone`, `company`, `position`, `memo`, `address`, `birthday`, `website`) VALUES ('23', 'https://www.gstatic.com/identity/boq/profilepicturepicker/photo_silhouette_e02a5f5deb3ffc173119a01bc9575490.png', '박지훈', 'yeongsuim@example.com', '042-171-6808', '안이', '판매원', '', '서울특별시 성북구 도산대73거리', '1939-03-27', '');
INSERT INTO `kidsnote_contact`.`tb_contact` (`contact_id`, `profile`, `name`, `email`, `phone`, `company`, `position`, `memo`, `address`, `birthday`, `website`) VALUES ('24', 'https://www.gstatic.com/identity/boq/profilepicturepicker/photo_silhouette_e02a5f5deb3ffc173119a01bc9575490.png', '장경수', 'ji@example.net', '017-955-1777', '주식회사 김한김', '재배원', '', '', '2008-06-16', '');
INSERT INTO `kidsnote_contact`.`tb_contact` (`contact_id`, `profile`, `name`, `email`, `phone`, `company`, `position`, `memo`, `address`, `birthday`, `website`) VALUES ('25', 'https://www.gstatic.com/identity/boq/profilepicturepicker/photo_silhouette_e02a5f5deb3ffc173119a01bc9575490.png', '박성호', 'seoyeon30@example.net', '016-374-9508', '(유) 정', '판매원', '', '부산광역시 중랑구 봉은사446로', '1996-03-05', '');
INSERT INTO `kidsnote_contact`.`tb_contact` (`contact_id`, `profile`, `name`, `email`, `phone`, `company`, `position`, `memo`, `address`, `birthday`, `website`) VALUES ('26', 'https://www.gstatic.com/identity/boq/profilepicturepicker/photo_silhouette_e02a5f5deb3ffc173119a01bc9575490.png', '이정훈', 'gimbyeongceol@example.org', '032-610-5795', '김정', '행사기획자', '', '', '2002-08-13', 'sgo@gmail.com');
INSERT INTO `kidsnote_contact`.`tb_contact` (`contact_id`, `profile`, `name`, `email`, `phone`, `company`, `position`, `memo`, `address`, `birthday`, `website`) VALUES ('27', 'https://www.gstatic.com/identity/boq/profilepicturepicker/photo_silhouette_e02a5f5deb3ffc173119a01bc9575490.png', '백재호', 'gimsunog@example.net', '033-412-9166', '', '', '', '대구광역시 서초구 삼성1가 (성수이최면)', '1980-12-07', '');
INSERT INTO `kidsnote_contact`.`tb_contact` (`contact_id`, `profile`, `name`, `email`, `phone`, `company`, `position`, `memo`, `address`, `birthday`, `website`) VALUES ('28', 'https://www.gstatic.com/identity/boq/profilepicturepicker/photo_silhouette_e02a5f5deb3ffc173119a01bc9575490.png', '김경자', 'lgim@example.com', '018-816-6954', '', '', '', '', '1958-05-03', '');
INSERT INTO `kidsnote_contact`.`tb_contact` (`contact_id`, `profile`, `name`, `email`, `phone`, `company`, `position`, `memo`, `address`, `birthday`, `website`) VALUES ('29', 'https://www.gstatic.com/identity/boq/profilepicturepicker/photo_silhouette_e02a5f5deb3ffc173119a01bc9575490.png', '박현정', 'eunseo05@example.net', '051-224-1891', '', '', '', '강원도 부천시 소사구 잠실가 (진호이류면)', '2008-06-12', 'https://yuhanhoesa.kr/');
INSERT INTO `kidsnote_contact`.`tb_contact` (`contact_id`, `profile`, `name`, `email`, `phone`, `company`, `position`, `memo`, `address`, `birthday`, `website`) VALUES ('30', 'https://www.gstatic.com/identity/boq/profilepicturepicker/photo_silhouette_e02a5f5deb3ffc173119a01bc9575490.png', '오진우', 'hongjiyeong@example.net', '041-642-9650', '', '', '', '대전광역시 영등포구 가락로 (예진최마을)', '1947-03-20', '');

-- 라벨 데이터
INSERT INTO `kidsnote_contact`.`tb_label` (`label_id`, `label_name`) VALUES ('1', 'Lime');
INSERT INTO `kidsnote_contact`.`tb_label` (`label_id`, `label_name`) VALUES ('2', 'Beige');
INSERT INTO `kidsnote_contact`.`tb_label` (`label_id`, `label_name`) VALUES ('3', 'PeachPuff');
INSERT INTO `kidsnote_contact`.`tb_label` (`label_id`, `label_name`) VALUES ('4', 'FloralWhite');
INSERT INTO `kidsnote_contact`.`tb_label` (`label_id`, `label_name`) VALUES ('5', 'Lavender');

-- 연락처 라벨 매개 데이터
INSERT INTO `kidsnote_contact`.`tb_contact_label` (`contact_id`, `label_id`) VALUES ('1', '1');
INSERT INTO `kidsnote_contact`.`tb_contact_label` (`contact_id`, `label_id`) VALUES ('1', '2');
INSERT INTO `kidsnote_contact`.`tb_contact_label` (`contact_id`, `label_id`) VALUES ('3', '1');
